controller_frequency: 10
#controller_patience: 15.0
#oscillation_timeout: 10.0
#oscillation_distance: 0.5


TrajectoryPlannerROS:

  controller_frequency: 10.0 #verificar
  pdist_scale: 0.9

  max_vel_x: 0.2 # 0.3
  min_vel_x: 0.05 # 0.1
  max_vel_theta: 0.8 #1.0
  min_vel_theta: -0.8 #
  min_in_place_vel_theta: 0.01 # 0.4

  max_rotational_vel: 0.15 #
  min_in_place_rotational_vel: 0.01 # 0.5
  
  acc_lim_theta: 2.0 #1.5
  acc_lim_x: 2.0 #1.0
  acc_lim_y: 2.0 #1.0

  meter_scoring: false##

  

  holonomic_robot: false
