TrajectoryPlannerROS:
  max_vel_x: 0.1 # 0.3
  min_vel_x: 0.05 # 0.1
  max_vel_theta: 0.3 #1.0
  min_vel_theta: -0.3 #
  min_in_place_vel_theta: 0.01 # 0.4

  max_rotational_vel: 0.1 #
  min_in_place_rotational_vel: 0.01 #
  
  acc_lim_th: 1.0 #1.5
  acc_lim_x: 1.0 #1.0
  acc_lim_y: 1.0 #1.0

  meter_scoring: true##

  #controller_frequency: 10.0

  holonomic_robot: false
