map_type: costmap

obstacle_range: 6.0 #8.0 5.0
raytrace_range: 5.0 #10.0 6.0
footprint: [[-0.40,-0.32],[-0.40,0.32], [0.50, 0.32], [0.50,-0.32]]
#robot_radius: ir_of_robot
inflation_radius: 0.3

resolution: 0.05 #

cost_scaling_factor: 10.0#
observation_sources: scan
scan: {sensor_frame: /laser,  observation_persistence: 0.0, max_obstacle_height: 0.4, 
min_obstacle_height: 0.0, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

