obstacle_range: 5.0 #8.0
raytrace_range: 6.0 #10.0
footprint: [[-0.40,-0.32],[-0.40,0.32], [0.50, 0.32], [0.50,-0.32]]
#robot_radius: ir_of_robot
inflation_radius: 0.5

cost_scaling_factor: 10.0#
observation_sources: scan
scan: {sensor_frame: lms100,  observation_persistence: 0.0, max_obstacle_height: 0.4, min_obstacle_height: 0.0, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

