global_costmap:
  global_frame: /map
  robot_base_frame: /base_link #base_link
  update_frequency: 5.0 #5.0 A freqüência em Hz de frequência com que o mapa global é atualizado com as informações do sensor
  static_map: true
